// File generated by FlutterFire CLI.
// To regenerate this file with your real Firebase project, run:
//   flutterfire configure
//
// This file currently contains REPLACE_ME placeholders so the app compiles
// before you have wired your own Firebase project.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQpAafT-RUxKTtCiwdYSuj_gP3kNYd2g0',
    appId: '1:764987974329:android:89cf259c09995954dbb168',
    messagingSenderId: '764987974329',
    projectId: 'nawa-67728',
    storageBucket: 'nawa-67728.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABXe45wT9vUQjC-5LkbsbS3UnY6feAD18',
    appId: '1:764987974329:ios:4b18c79001948e98dbb168',
    messagingSenderId: '764987974329',
    projectId: 'nawa-67728',
    storageBucket: 'nawa-67728.firebasestorage.app',
    androidClientId: '764987974329-diqu2vhq1m13n6dpi8vimgmb84vbged7.apps.googleusercontent.com',
    iosClientId: '764987974329-otqlc6r6liqrcb4th783eni7c8l27r6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.nawaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_ME_MACOS_API_KEY',
    appId: 'REPLACE_ME_MACOS_APP_ID',
    messagingSenderId: 'REPLACE_ME_SENDER_ID',
    projectId: 'REPLACE_ME_PROJECT_ID',
    storageBucket: 'REPLACE_ME_PROJECT_ID.appspot.com',
    iosBundleId: 'app.nawa.nawa',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME_WEB_API_KEY',
    appId: 'REPLACE_ME_WEB_APP_ID',
    messagingSenderId: 'REPLACE_ME_SENDER_ID',
    projectId: 'REPLACE_ME_PROJECT_ID',
    authDomain: 'REPLACE_ME_PROJECT_ID.firebaseapp.com',
    storageBucket: 'REPLACE_ME_PROJECT_ID.appspot.com',
  );
}