import 'dart:async';

import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../app/providers.dart';
import '../../core/constants/app_constants.dart';
import '../../domain/entities/note.dart';
import '../../domain/entities/note_block.dart';

class NoteEditorState {
  final Note? note;
  final bool loading;
  final bool saving;
  final DateTime? lastSavedAt;
  final String? aiBusyAction;

  const NoteEditorState({
    this.note,
    this.loading = true,
    this.saving = false,
    this.lastSavedAt,
    this.aiBusyAction,
  });

  NoteEditorState copyWith({
    Note? note,
    bool? loading,
    bool? saving,
    DateTime? lastSavedAt,
    String? aiBusyAction,
    bool clearAiBusy = false,
  }) =>
      NoteEditorState(
        note: note ?? this.note,
        loading: loading ?? this.loading,
        saving: saving ?? this.saving,
        lastSavedAt: lastSavedAt ?? this.lastSavedAt,
        aiBusyAction: clearAiBusy ? null : (aiBusyAction ?? this.aiBusyAction),
      );
}

class NoteEditorViewModel
    extends FamilyNotifier<NoteEditorState, String> {
  Timer? _saveTimer;
  String? _noteId;

  @override
  NoteEditorState build(String noteId) {
    _noteId = noteId;
    Future.microtask(_load);
    ref.onDispose(() {
      _saveTimer?.cancel();
    });
    return const NoteEditorState();
  }

  Future<void> _load() async {
    final id = _noteId!;
    final repo = ref.read(noteRepositoryProvider);
    final r = await repo.getNote(id);
    final note = r.dataOrNull;
    final auth = ref.read(authStateProvider).value;
    if (note != null) {
      state = state.copyWith(note: note, loading: false);
    } else if (auth != null) {
      // create a fresh note with this id (generated by router)
      final created = Note.create(userId: auth.uid).copyWith();
      // override id to match route
      final asMap = created.toMap()..['id'] = id;
      state = state.copyWith(
        note: Note.fromMap(asMap),
        loading: false,
      );
      await repo.saveNote(state.note!);
    } else {
      state = state.copyWith(loading: false);
    }
  }

  void updateTitle(String title) {
    final n = state.note;
    if (n == null) return;
    state = state.copyWith(note: n.copyWith(title: title));
    _scheduleSave();
  }

  void updateBlock(NoteBlock block) {
    final n = state.note;
    if (n == null) return;
    final blocks = [...n.blocks];
    final idx = blocks.indexWhere((b) => b.id == block.id);
    if (idx == -1) return;
    blocks[idx] = block;
    state = state.copyWith(note: n.copyWith(blocks: blocks));
    _scheduleSave();
  }

  void addBlock(NoteBlock block) {
    final n = state.note;
    if (n == null) return;
    state = state.copyWith(note: n.copyWith(blocks: [...n.blocks, block]));
    _scheduleSave();
  }

  void insertBlockAfter(String afterId, NoteBlock block) {
    final n = state.note;
    if (n == null) return;
    final blocks = [...n.blocks];
    final i = blocks.indexWhere((b) => b.id == afterId);
    if (i == -1) {
      blocks.add(block);
    } else {
      blocks.insert(i + 1, block);
    }
    state = state.copyWith(note: n.copyWith(blocks: blocks));
    _scheduleSave();
  }

  void removeBlock(String blockId) {
    final n = state.note;
    if (n == null) return;
    final blocks = n.blocks.where((b) => b.id != blockId).toList();
    if (blocks.isEmpty) blocks.add(NoteBlockFactory.newText());
    state = state.copyWith(note: n.copyWith(blocks: blocks));
    _scheduleSave();
  }

  void reorder(int oldIndex, int newIndex) {
    final n = state.note;
    if (n == null) return;
    final blocks = [...n.blocks];
    if (newIndex > oldIndex) newIndex -= 1;
    final item = blocks.removeAt(oldIndex);
    blocks.insert(newIndex, item);
    state = state.copyWith(note: n.copyWith(blocks: blocks));
    _scheduleSave();
  }

  void setTags(List<String> tags) {
    final n = state.note;
    if (n == null) return;
    state = state.copyWith(note: n.copyWith(tags: tags));
    _scheduleSave();
  }

  void setReminder(DateTime? when) {
    final n = state.note;
    if (n == null) return;
    state = state.copyWith(
      note: when == null
          ? n.copyWith(clearReminder: true)
          : n.copyWith(reminderAt: when),
    );
    _scheduleSave();
  }

  void setPinned(bool value) {
    final n = state.note;
    if (n == null) return;
    state = state.copyWith(note: n.copyWith(pinned: value));
    _scheduleSave();
  }

  void setArchived(bool value) {
    final n = state.note;
    if (n == null) return;
    state = state.copyWith(note: n.copyWith(archived: value));
    _scheduleSave();
  }

  void setEncrypted(bool value) {
    final n = state.note;
    if (n == null) return;
    state = state.copyWith(note: n.copyWith(encrypted: value));
    _scheduleSave();
  }

  void setWorkspace(String? wsId) {
    final n = state.note;
    if (n == null) return;
    state = state.copyWith(
      note: wsId == null
          ? n.copyWith(clearWorkspace: true)
          : n.copyWith(workspaceId: wsId),
    );
    _scheduleSave();
  }

  void setSummary(String? summary) {
    final n = state.note;
    if (n == null) return;
    state = state.copyWith(note: n.copyWith(aiSummary: summary));
    _scheduleSave();
  }

  void updateFontStyle(NoteFontStyle style) {
    final n = state.note;
    if (n == null) return;
    state = state.copyWith(note: n.copyWith(fontStyle: style));
    _scheduleSave();
  }

  void setAiBusy(String? action) {
    state = state.copyWith(aiBusyAction: action, clearAiBusy: action == null);
  }

  void _scheduleSave() {
    _saveTimer?.cancel();
    _saveTimer = Timer(
      const Duration(milliseconds: AppLimits.autoSaveDebounceMs),
      _persist,
    );
  }

  Future<void> _persist() async {
    final n = state.note;
    if (n == null) return;
    state = state.copyWith(saving: true);
    await ref.read(noteRepositoryProvider).saveNote(n);
    state = state.copyWith(saving: false, lastSavedAt: DateTime.now());
  }

  Future<void> saveNow() async {
    _saveTimer?.cancel();
    await _persist();
  }

  Future<void> deleteSelf() async {
    final n = state.note;
    if (n == null) return;
    await ref.read(noteRepositoryProvider).deleteNote(n.id);
  }

  String fullPlainText() {
    final n = state.note;
    if (n == null) return '';
    final buffer = StringBuffer();
    if (n.title.isNotEmpty) buffer.writeln(n.title);
    for (final b in n.blocks) {
      switch (b) {
        case TextBlock t:
          buffer.writeln(t.text);
        case ChecklistBlock c:
          for (final item in c.items) {
            buffer.writeln('- ${item.text}');
          }
        case ImageBlock i:
          if (i.caption.isNotEmpty) buffer.writeln(i.caption);
        case AudioBlock a:
          if (a.transcript.isNotEmpty) buffer.writeln(a.transcript);
        case VideoBlock v:
          if (v.caption.isNotEmpty) buffer.writeln(v.caption);
        case LinkBlock l:
          buffer.writeln(l.title ?? l.url);
        case FileBlock f:
          buffer.writeln(f.fileName);
      }
    }
    return buffer.toString();
  }
}

final noteEditorViewModelProvider =
    NotifierProvider.family<NoteEditorViewModel, NoteEditorState, String>(
        NoteEditorViewModel.new);
